color: amber
description: null
fieldLayouts:
  c8bf080b-0903-4f94-b5f0-7920c5ece469:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-07T18:49:01+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 41218836-6831-49f3-9a90-01aff59d5439 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3130ebec-e073-4c17-a531-c3b6ef46d879
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e327c67c-c152-4e0c-b719-241214c2c37c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-07-26T20:15:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3e18e51e-c692-4a4c-86b7-8cb0277cfed7 # Text
            handle: caption
            includeInCards: true
            instructions: 'Optional. The image''s own caption is used automatically — only fill this in if you want a different caption for this article.'
            label: 'Caption Override'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bdab4fa9-e117-423e-bae4-578d14e041ba
            userCondition: null
            warning: null
            width: 100
        name: Overrides
        uid: b91a1117-8e24-42da-9286-70dc69b2a0a7
        userCondition: null
handle: image
hasTitleField: false
icon: file-image
name: Image
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
