#!/bin/bash

## Description: Sync production database and assets to local DDEV

set -e

RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[1;34m'
RESET='\033[0m'

DB_NAME="sumner_mission_blog"
DB_USER="sumnermissionblog"
DB_PASSWORD="Y24a!exJ*9s4rv*yUTQb"
REMOTE_HOST="mlj.one"
REMOTE_DIR="/var/www/sumnermission.org/web"

echo -e "${YELLOW}Exporting remote database...${RESET}"
ssh matt@${REMOTE_HOST} "mysqldump -u ${DB_USER} -p'${DB_PASSWORD}' ${DB_NAME} > /tmp/sumner_sync.sql"

echo -e "${YELLOW}Downloading database...${RESET}"
scp matt@${REMOTE_HOST}:/tmp/sumner_sync.sql /tmp/sumner_sync.sql

echo -e "${YELLOW}Importing to DDEV...${RESET}"
ddev import-db --file=/tmp/sumner_sync.sql

echo -e "${YELLOW}Cleaning up...${RESET}"
ssh matt@${REMOTE_HOST} "rm /tmp/sumner_sync.sql"
rm /tmp/sumner_sync.sql

echo -e "${YELLOW}Syncing images...${RESET}"
rsync -avz --progress matt@${REMOTE_HOST}:${REMOTE_DIR}/images/ ./web/images/

echo -e "${BLUE}Sync complete!${RESET}"
